### ISSUE TITLE
What versions of Visual Studio are supported and outdated documentation?

### ISSUE THREAD

**Issue by MarneeDear** [bmostafa87/messages-csharp-sdk#7]
What versions of Visual Studio are supported? I tried in VS 2015 but it fails to load the SDK project.

Also the documentation doesnt line up with the latest version of the MessageMedia dlls. Can you please update the documentation?

**Comment by IbrahimTareq** [comment]
Unfortunately, we don't support multiple versions of the SDK project yet. The current SDK project uses the .NET standard project format which VS2017 supports natively. If you're looking to contribute, feel free to build a version for VS 2015 or if you're trying to use the SDK to send messages, my advice would be looking at the "Installing via NuGet" section of the readme.

The documentation has been updated. Thanks for pointing that out!
